apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: CLUSTER_CERT
    server: https://CLUSTER_ADDR
  name: CLUSTER_NAME
contexts:
- context:
    cluster: CLUSTER_NAME
    user: USER_NAME
  name: USER_NAME@CLUSTER_NAME
kind: Config
users:
- name: USER_NAME
  user:
    client-certificate-data: CLIENT_CERT_DATA
    client-key-data: CLIENT_KEY_DATA